import { type Address } from 'viem'

type ContractAddresses = {
  USDC: Address
  DXY_BEAR: Address
  DXY_BULL: Address
  SDXY_BEAR: Address
  SDXY_BULL: Address
  PLETH_CORE: Address
  CURVE_POOL: Address
  ZAP_ROUTER: Address
  LEVERAGE_ROUTER: Address
  BULL_LEVERAGE_ROUTER: Address
  STAKING_BEAR: Address
  STAKING_BULL: Address
  MORPHO_POOL: Address
  BASKET_ORACLE: Address
}

// Placeholder addresses - replace with actual deployed contract addresses
const PLACEHOLDER: Address = '0x0000000000000000000000000000000000000000'

export const MAINNET_ADDRESSES: ContractAddresses = {
  USDC: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', // Real USDC on mainnet
  DXY_BEAR: PLACEHOLDER,
  DXY_BULL: PLACEHOLDER,
  SDXY_BEAR: PLACEHOLDER,
  SDXY_BULL: PLACEHOLDER,
  PLETH_CORE: PLACEHOLDER,
  CURVE_POOL: PLACEHOLDER,
  ZAP_ROUTER: PLACEHOLDER,
  LEVERAGE_ROUTER: PLACEHOLDER,
  BULL_LEVERAGE_ROUTER: PLACEHOLDER,
  STAKING_BEAR: PLACEHOLDER,
  STAKING_BULL: PLACEHOLDER,
  MORPHO_POOL: PLACEHOLDER,
  BASKET_ORACLE: PLACEHOLDER,
}

export const SEPOLIA_ADDRESSES: ContractAddresses = {
  USDC: PLACEHOLDER, // Replace with Sepolia USDC address
  DXY_BEAR: PLACEHOLDER,
  DXY_BULL: PLACEHOLDER,
  SDXY_BEAR: PLACEHOLDER,
  SDXY_BULL: PLACEHOLDER,
  PLETH_CORE: PLACEHOLDER,
  CURVE_POOL: PLACEHOLDER,
  ZAP_ROUTER: PLACEHOLDER,
  LEVERAGE_ROUTER: PLACEHOLDER,
  BULL_LEVERAGE_ROUTER: PLACEHOLDER,
  STAKING_BEAR: PLACEHOLDER,
  STAKING_BULL: PLACEHOLDER,
  MORPHO_POOL: PLACEHOLDER,
  BASKET_ORACLE: PLACEHOLDER,
}

export function getAddresses(chainId: number): ContractAddresses {
  switch (chainId) {
    case 1:
      return MAINNET_ADDRESSES
    case 11155111:
      return SEPOLIA_ADDRESSES
    default:
      return MAINNET_ADDRESSES
  }
}
